name: Dispatch
run-name: Dispatched Repository Actions - ${{ inputs.job }} ⌛️
on:
  workflow_dispatch:
    inputs:
      job:
        description: Dispatch job to run
        required: true
        type: choice
        options:
          - build
      config:
        description: Build configuration
        required: true
        default: RelWithDebInfo
        type: choice
        options:
          - RelWithDebInfo
          - Release
          - Debug
          - MinSizeRel
      package:
        description: Create native installer packages
        required: true
        default: false
        type: boolean
permissions:
  contents: read
concurrency:
  group: manual-build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-and-build:
    if: inputs.job == 'build'
    uses: ./.github/workflows/build-project.yaml
    with:
      config: ${{ inputs.config }}
      package: ${{ inputs.package }}
    secrets: inherit
